name: Rust Project
on:
  push:
    branches:
      master
jobs: 
  build:
    runs-on: ubuntu-22.04 
    permissions:
     packages: cargo

    steps:
        # Checkout the repository code
       
      - name: Checkout code
        uses: actions/checkout@v3

       
      - name: Logn to Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check code
        run: cargo check
      - name: Build Project
        run: cargo build

       
      - name: Build Project
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: | 
            ghcr.io/${{ vars.REPOSITORY }}:latest
            ghcr.io/${{ vars.REPOSITORY }}:${{ github.run_number }}
